# Generated by Django 5.0.3 on 2024-03-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0002_demand_delete_rapper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demand",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="demand",
            name="demand_A",
        ),
        migrations.RemoveField(
            model_name="demand",
            name="demand_B",
        ),
        migrations.RemoveField(
            model_name="demand",
            name="demand_C",
        ),
        migrations.RemoveField(
            model_name="demand",
            name="demand_D",
        ),
        migrations.CreateModel(
            name="DemandBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_number", models.IntegerField()),
                ("demand_value", models.IntegerField()),
                (
                    "demand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapi.demand"
                    ),
                ),
            ],
        ),
    ]
