# Generated by Django 5.0.3 on 2024-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0003_remove_demand_branch_remove_demand_demand_a_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="demandbranch",
            old_name="demand_value",
            new_name="demand_product_A_value",
        ),
        migrations.AddField(
            model_name="demandbranch",
            name="demand_product_B_value",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="demandbranch",
            name="demand_product_C_value",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="demandbranch",
            name="demand_product_D_value",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
