# Generated by Django 5.0.3 on 2024-03-28 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0005_alter_demandbranch_demand_product_a_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="day",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_number", models.IntegerField()),
                (
                    "demand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="myapi.demand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProductA", models.IntegerField()),
                ("ProductB", models.IntegerField()),
                ("ProductC", models.IntegerField()),
                ("ProductD", models.IntegerField()),
                ("Gender", models.IntegerField()),
                ("Age", models.IntegerField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="myapi.branch",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DemandBranch",
        ),
    ]
