# Generated by Django 5.0.3 on 2024-03-28 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0006_alter_demand_day_branch_transaction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="ProductA",
            new_name="productA",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="ProductB",
            new_name="productB",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="ProductC",
            new_name="productC",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="ProductD",
            new_name="productD",
        ),
    ]
